config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  
  resources :charges
  resources :events

  get "events/subscribe/:id", to: "events#subscribe"
  get "events/closingevent/:id", to: "events#closingevent"
  post "events/pay/:id", to: "events#pay", as: "pay"
  get "events/subscribeandpay/:id", to: "events#subscribeandpay"
  get "events/after_pay/:id", to: "events#after_pay", as: 'after_pay'

  get "events/ele/:ele_id/:id", to: "events#addeletoinvitation"
  get "events/pro/:pro_id/:id", to: "events#addprotoinvitation"
  
  devise_for :pros, :controllers => { registrations: 'registrations_pro' }
  devise_for :eles, :controllers => { registrations: 'registrations_ele' }

  get "eles/index", to: "eles#index", as: "eles"
  get "eles/show/:id", to: "eles#show", as: "ele"
  get "pros/index", to: "pros#index", as: "pros"
  get "pros/show/:id", to: "pros#show", as: "pro"

end

app/models/ele.rb
class Ele < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable

  has_many :created_events, class_name: "Event", foreign_key: :creator_id
  has_and_belongs_to_many :eleattended_events, class_name: "Event"
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/eles_controller.rb
class ElesController < ApplicationController
    def index
        @eles = Ele.all
    end
    
    def show
        @ele = Ele.find(params[:id])
    end
end

app/helpers/eles_helper.rb
module ElesHelper
end

app/views/eles/index.html.erb
<div class="container">
<h1> Les élèves </h1></br></br>
  <div class="row">
    <% @eles.each do |ele|%>
        <div class="col-lg-4 mb-4">
        <div class="card h-100">
            <h4 class="card-header"><%= ele.firstname %></h4>
                <div class="card-body">
                    <p class="card-text">Passions : <%= ele.passion1 %>, <%= ele.passion2 %>, <%= ele.passion3 %>, <%= ele.passion4 %> </p>
                    <p class="card-text">Ville : <%= ele.ville %> </p>
                </div>
                <div class="card-footer">
                <p> <%= link_to 'Voir son profil', ele_path(ele) %> </p>
                </div>
        </div>
        </div>
    <% end %>
  </div>
</div>

app/views/eles/show.html.erb
<div class="container">
  <div class="row">
    <h1 class="card-header"><%= @ele.firstname %></h1>
        <div class="card-body">
            <p class="card-text">Passions : <%= @ele.passion1 %>, <%= @ele.passion2 %>, <%= @ele.passion3 %>, <%= @ele.passion4 %> </p>
            <p class="card-text">Ville : <%= @ele.ville %> </p>
            <p class="card-text">Mail : <%= @ele.email %> </p>
        </div>
  </div>


    </br></br>


    <h1>Les événements que <%=@ele.firstname%>  a créé </h1>



    <div class="row">
        <% if !@ele.created_events.empty? %>
            <% @ele.created_events.each do |event| %>
                <div class="col-lg-4 mb-4">
                    <div class="card h-100">
                        <h4 class="card-header"><%= event.name %></h4>
                            <div class="card-body">
                                <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                            </div>
                            <div class="card-footer">
                            <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                            </div>
                    </div>
                </div>
            <% end %>
        <% else %>
            <p> <%= @ele.firstname %> n a pour le moment créer aucun event </p>
        <% end %>
    </div>


    </br></br>


    <h1>Les événements auxquels <%=@ele.firstname%>  a participé </h1>


    <div class="row">
        <% if !@ele.eleattended_events.empty? %>
            <% @ele.eleattended_events.each do |event| %>
                <div class="col-lg-4 mb-4">
                    <div class="card h-100">
                        <h4 class="card-header"><%= event.name %></h4>
                            <div class="card-body">
                                <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                            </div>
                            <div class="card-footer">
                                <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                            </div>
                    </div>
                </div>
            <% end %>
        <% else %>
            <p> <%= @ele.firstname %> n a pour le moment aucune activité </p>
        <% end %>
    </div>



    <% if !@ele.eleattended_events.empty? %>
        <% @ele.eleattended_events.each do |event| %>
                <% if !event.apayer.nil? %>
                    <% if event.apayer.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer2.nil? %>
                    <% if event.apayer2.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer3.nil? %>
                    <% if event.apayer3.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer4.nil? %>
                    <% if event.apayer4.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer5.nil? %>
                    <% if event.apayer5.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer6.nil? %>
                    <% if event.apayer6.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer7.nil? %>
                    <% if event.apayer7.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer8.nil? %>
                    <% if event.apayer8.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer9.nil? %>
                    <% if event.apayer9.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% elsif !event.apayer10.nil? %>
                    <% if event.apayer10.to_s.include? @ele.id.to_s %>
                    <div class="col-lg-4 mb-4">
                        <div class="card h-100">
                            <h4 class="card-header"><%= event.name %></h4>
                                <div class="card-body">
                                    <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                                </div>
                                <div class="card-footer">
                                    <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                                </div>
                        </div>
                    </div>
                    <% else %>
                    <% end %>
                <% else %>
                <% end %>
        <% end %>
    <% else %>
        <p> <%=@ele.firstname%> n a pour le moment aucune activité </p>
    <% end %>
    </br></br>


    <h1>Tous les evenement à venir qui intéressent <%=@ele.firstname%> </h1>




    <div class="row">
        <% if !@ele.eleattended_events.empty? %>
            <% @ele.eleattended_events.each do |event| %>
                <div class="col-lg-4 mb-4">
                    <div class="card h-100">
                        <h4 class="card-header"><%= event.name %></h4>
                            <div class="card-body">
                                <p class="card-text">Discipline : <%= event.discipline %> </br>Description : <%= event.description %></br> Date: <%= event.date %></br> </p>
                            </div>
                            <div class="card-footer">
                                <p> <%= link_to 'Voir l event', event_path(event) %> </p>
                            </div>
                    </div>
                </div>
            <% end %>
        <% else %>
            <p> <%= @ele.firstname %> n a pour le moment aucune activité </p>
        <% end %>
    </div>

</div>