config/routes.rb
Rails.application.routes.draw do
  
  root 'events#index'
  
  resources :charges
  resources :events

  get "events/subscribe/:id", to: "events#subscribe"
  get "events/closingevent/:id", to: "events#closingevent"
  post "events/pay/:id", to: "events#pay", as: "pay"
  get "events/subscribeandpay/:id", to: "events#subscribeandpay"
  get "events/after_pay/:id", to: "events#after_pay", as: 'after_pay'

  get "events/ele/:ele_id/:id", to: "events#addeletoinvitation"
  get "events/pro/:pro_id/:id", to: "events#addprotoinvitation"
  
  devise_for :pros, :controllers => { registrations: 'registrations_pro' }
  devise_for :eles, :controllers => { registrations: 'registrations_ele' }

  get "eles/index", to: "eles#index", as: "eles"
  get "eles/show/:id", to: "eles#show", as: "ele"
  get "pros/index", to: "pros#index", as: "pros"
  get "pros/show/:id", to: "pros#show", as: "pro"

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <ul class="nav navbar-nav">
            <% if ele_signed_in? %>
              <li><%= current_ele.email %>, vous êtes connecté en tant qu'élève</li>
              <li><%= link_to destroy_ele_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out"></span> Logout<%end%></li>
            <% elsif pro_signed_in? %>
              <li><%= current_pro.email %>, vous êtes connecté en tant que professeur</li>
              <li><%= link_to destroy_pro_session_path, method: :delete do %><span class="glyphicon glyphicon-log-out"></span> Logout<%end%></li>
            <% else %>
            <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right"style="margin-right:10px; margin-top:1.3%;">
          <li class="active"><a href="/">RECHERCHER UN EVENT</a></li>
          <% if ele_signed_in? %>
            <li><%= link_to eles_path do %><span class="glyphicon glyphicon-user"></span>Rechercher un élève<%end%></li>
            <li><%= link_to pros_path do %><span class="glyphicon glyphicon-user"></span>Rechercher un prof<%end%></li>
            <li><%= link_to new_event_path do %><span class="glyphicon glyphicon-user"></span>Créer un événement<%end%></li>
          <% elsif pro_signed_in? %>
            <li><%= link_to eles_path do %><span class="glyphicon glyphicon-user"></span>Rechercher un élève<%end%></li>
            <li><%= link_to pros_path do %><span class="glyphicon glyphicon-user"></span>Rechercher un prof<%end%></li>
            <li><%= link_to new_event_path do %><span class="glyphicon glyphicon-user"></span>Créer un événement<%end%></li>
          <% else %>
            <li><%= link_to new_ele_registration_path do %><span class="glyphicon glyphicon-user"></span> Créer compte élève<%end%></li>
            <li><%= link_to new_pro_registration_path do %><span class="glyphicon glyphicon-user"></span> Créer compte professeur<%end%></li>
            <li><%= link_to new_ele_session_path do %><span class="glyphicon glyphicon-log-in"></span> Connecter élève<%end%></li>
            <li><%= link_to new_pro_session_path do %><span class="glyphicon glyphicon-log-in"></span> Connecter professeur<%end%></li>
          <% end %>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UH</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


    <!-- Bootstrap core CSS -->
    <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://blackrockdigital.github.io/startbootstrap-modern-business/css/modern-business.css" rel="stylesheet">


  </head>

  <body>
    <%= render "layouts/header" %>
    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>